/*
 * Created on 16 Mar 2017 ( Time 18:41:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.model;

import java.io.Serializable;

import javax.validation.constraints.*;


public class PersonAssignment implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer personIdperson;
    @NotNull
    private Integer requirementIdrequirement;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Integer status;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setPersonIdperson( Integer personIdperson ) {
        this.personIdperson = personIdperson ;
    }

    public Integer getPersonIdperson() {
        return this.personIdperson;
    }

    public void setRequirementIdrequirement( Integer requirementIdrequirement ) {
        this.requirementIdrequirement = requirementIdrequirement ;
    }

    public Integer getRequirementIdrequirement() {
        return this.requirementIdrequirement;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setStatus( Integer status ) {
        this.status = status;
    }
    public Integer getStatus() {
        return this.status;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(personIdperson);
        sb.append("|");
        sb.append(requirementIdrequirement);
        sb.append("|");
        sb.append(status);
        return sb.toString(); 
    } 


}
