/*
 * Created on 16 Mar 2017 ( Time 18:41:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.model;

import java.io.Serializable;

import javax.validation.constraints.*;


public class RequirementSpecificationType implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer requirementIdrequirement;
    @NotNull
    private Integer specificationTypeIdrequirementType;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    


    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setRequirementIdrequirement( Integer requirementIdrequirement ) {
        this.requirementIdrequirement = requirementIdrequirement ;
    }

    public Integer getRequirementIdrequirement() {
        return this.requirementIdrequirement;
    }

    public void setSpecificationTypeIdrequirementType( Integer specificationTypeIdrequirementType ) {
        this.specificationTypeIdrequirementType = specificationTypeIdrequirementType ;
    }

    public Integer getSpecificationTypeIdrequirementType() {
        return this.specificationTypeIdrequirementType;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(requirementIdrequirement);
        sb.append("|");
        sb.append(specificationTypeIdrequirementType);
        return sb.toString(); 
    } 


}
