/*
 * Created on 16 Mar 2017 ( Time 18:41:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.model;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Requirement implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer idrequirement;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 75 )
    private String title;

    @Size( max = 16777215 )
    private String description;

    @Size( max = 16777215 )
    private String acceptanceCriteria;


    private Date createdOn;


    private Integer createdBy;


    private Date startDate;


    private Date endDate;


    private Integer status;

    @NotNull
    private Integer statusCodeId;


    private Integer priority;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdrequirement( Integer idrequirement ) {
        this.idrequirement = idrequirement ;
    }

    public Integer getIdrequirement() {
        return this.idrequirement;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setTitle( String title ) {
        this.title = title;
    }
    public String getTitle() {
        return this.title;
    }

    public void setDescription( String description ) {
        this.description = description;
    }
    public String getDescription() {
        return this.description;
    }

    public void setAcceptanceCriteria( String acceptanceCriteria ) {
        this.acceptanceCriteria = acceptanceCriteria;
    }
    public String getAcceptanceCriteria() {
        return this.acceptanceCriteria;
    }

    public void setCreatedOn( Date createdOn ) {
        this.createdOn = createdOn;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedBy( Integer createdBy ) {
        this.createdBy = createdBy;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setStartDate( Date startDate ) {
        this.startDate = startDate;
    }
    public Date getStartDate() {
        return this.startDate;
    }

    public void setEndDate( Date endDate ) {
        this.endDate = endDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }

    public void setStatus( Integer status ) {
        this.status = status;
    }
    public Integer getStatus() {
        return this.status;
    }

    public void setStatusCodeId( Integer statusCodeId ) {
        this.statusCodeId = statusCodeId;
    }
    public Integer getStatusCodeId() {
        return this.statusCodeId;
    }

    public void setPriority( Integer priority ) {
        this.priority = priority;
    }
    public Integer getPriority() {
        return this.priority;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idrequirement);
        sb.append("|");
        sb.append(title);
        // attribute 'description' not usable (type = String Long Text)
        // attribute 'acceptanceCriteria' not usable (type = String Long Text)
        sb.append("|");
        sb.append(createdOn);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(startDate);
        sb.append("|");
        sb.append(endDate);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(statusCodeId);
        sb.append("|");
        sb.append(priority);
        return sb.toString(); 
    } 


}
