/*
 * Created on 16 Mar 2017 ( Time 18:41:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import net.kumasi.storytime.web.common.AbstractController;
import net.kumasi.storytime.web.common.FormMode;
import net.kumasi.storytime.web.common.Message;
import net.kumasi.storytime.web.common.MessageType;

//--- Entities
import net.kumasi.storytime.model.Comment;
import net.kumasi.storytime.model.Requirement;

//--- Services 
import net.kumasi.storytime.business.service.CommentService;
import net.kumasi.storytime.business.service.RequirementService;

//--- List Items 
import net.kumasi.storytime.web.listitem.RequirementListItem;

/**
 * Spring MVC controller for 'Comment' management.
 */
@Controller
@RequestMapping("/comment")
public class CommentController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "comment";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "comment/form";
	private static final String JSP_LIST   = "comment/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/comment/create";
	private static final String SAVE_ACTION_UPDATE   = "/comment/update";

	//--- Main entity service
	@Resource
    private CommentService commentService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private RequirementService requirementService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public CommentController() {
		super(CommentController.class, MAIN_ENTITY_NAME );
		log("CommentController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "Requirement"
	 * @param model
	 */
	private void populateListOfRequirementItems(Model model) {
		List<Requirement> list = requirementService.findAll();
		List<RequirementListItem> items = new LinkedList<RequirementListItem>();
		for ( Requirement requirement : list ) {
			items.add(new RequirementListItem( requirement ) );
		}
		model.addAttribute("listOfRequirementItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param comment
	 */
	private void populateModel(Model model, Comment comment, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, comment);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfRequirementItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfRequirementItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of Comment found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<Comment> list = commentService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new Comment
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		Comment comment = new Comment();	
		populateModel( model, comment, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing Comment
	 * @param model Spring MVC model
	 * @param idcomment  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{idcomment}")
	public String formForUpdate(Model model, @PathVariable("idcomment") Integer idcomment ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		Comment comment = commentService.findById(idcomment);
		populateModel( model, comment, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param comment  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid Comment comment, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				Comment commentCreated = commentService.create(comment); 
				model.addAttribute(MAIN_ENTITY_NAME, commentCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, comment.getIdcomment() );
			} else {
				populateModel( model, comment, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "comment.error.create", e);
			populateModel( model, comment, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param comment  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid Comment comment, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				Comment commentSaved = commentService.update(comment);
				model.addAttribute(MAIN_ENTITY_NAME, commentSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, comment.getIdcomment());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, comment, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "comment.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, comment, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param idcomment  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{idcomment}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("idcomment") Integer idcomment) {
		log("Action 'delete'" );
		try {
			commentService.delete( idcomment );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "comment.error.delete", e);
		}
		return redirectToList();
	}

}
