/*
 * Created on 16 Mar 2017 ( Time 18:41:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import net.kumasi.storytime.web.common.AbstractController;
import net.kumasi.storytime.web.common.FormMode;
import net.kumasi.storytime.web.common.Message;
import net.kumasi.storytime.web.common.MessageType;

//--- Entities
import net.kumasi.storytime.model.PersonAssignment;
import net.kumasi.storytime.model.Person;
import net.kumasi.storytime.model.Requirement;

//--- Services 
import net.kumasi.storytime.business.service.PersonAssignmentService;
import net.kumasi.storytime.business.service.PersonService;
import net.kumasi.storytime.business.service.RequirementService;

//--- List Items 
import net.kumasi.storytime.web.listitem.PersonListItem;
import net.kumasi.storytime.web.listitem.RequirementListItem;

/**
 * Spring MVC controller for 'PersonAssignment' management.
 */
@Controller
@RequestMapping("/personAssignment")
public class PersonAssignmentController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "personAssignment";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "personAssignment/form";
	private static final String JSP_LIST   = "personAssignment/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/personAssignment/create";
	private static final String SAVE_ACTION_UPDATE   = "/personAssignment/update";

	//--- Main entity service
	@Resource
    private PersonAssignmentService personAssignmentService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private PersonService personService; // Injected by Spring
	@Resource
    private RequirementService requirementService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public PersonAssignmentController() {
		super(PersonAssignmentController.class, MAIN_ENTITY_NAME );
		log("PersonAssignmentController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "Person"
	 * @param model
	 */
	private void populateListOfPersonItems(Model model) {
		List<Person> list = personService.findAll();
		List<PersonListItem> items = new LinkedList<PersonListItem>();
		for ( Person person : list ) {
			items.add(new PersonListItem( person ) );
		}
		model.addAttribute("listOfPersonItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "Requirement"
	 * @param model
	 */
	private void populateListOfRequirementItems(Model model) {
		List<Requirement> list = requirementService.findAll();
		List<RequirementListItem> items = new LinkedList<RequirementListItem>();
		for ( Requirement requirement : list ) {
			items.add(new RequirementListItem( requirement ) );
		}
		model.addAttribute("listOfRequirementItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param personAssignment
	 */
	private void populateModel(Model model, PersonAssignment personAssignment, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, personAssignment);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfPersonItems(model);
			populateListOfRequirementItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of PersonAssignment found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<PersonAssignment> list = personAssignmentService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new PersonAssignment
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		PersonAssignment personAssignment = new PersonAssignment();	
		populateModel( model, personAssignment, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing PersonAssignment
	 * @param model Spring MVC model
	 * @param personIdperson  primary key element
	 * @param requirementIdrequirement  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{personIdperson}/{requirementIdrequirement}")
	public String formForUpdate(Model model, @PathVariable("personIdperson") Integer personIdperson, @PathVariable("requirementIdrequirement") Integer requirementIdrequirement ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		PersonAssignment personAssignment = personAssignmentService.findById(personIdperson, requirementIdrequirement);
		populateModel( model, personAssignment, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param personAssignment  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid PersonAssignment personAssignment, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				PersonAssignment personAssignmentCreated = personAssignmentService.create(personAssignment); 
				model.addAttribute(MAIN_ENTITY_NAME, personAssignmentCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, personAssignment.getPersonIdperson(), personAssignment.getRequirementIdrequirement() );
			} else {
				populateModel( model, personAssignment, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "personAssignment.error.create", e);
			populateModel( model, personAssignment, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param personAssignment  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid PersonAssignment personAssignment, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				PersonAssignment personAssignmentSaved = personAssignmentService.update(personAssignment);
				model.addAttribute(MAIN_ENTITY_NAME, personAssignmentSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, personAssignment.getPersonIdperson(), personAssignment.getRequirementIdrequirement());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, personAssignment, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "personAssignment.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, personAssignment, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param personIdperson  primary key element
	 * @param requirementIdrequirement  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{personIdperson}/{requirementIdrequirement}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("personIdperson") Integer personIdperson, @PathVariable("requirementIdrequirement") Integer requirementIdrequirement) {
		log("Action 'delete'" );
		try {
			personAssignmentService.delete( personIdperson, requirementIdrequirement );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "personAssignment.error.delete", e);
		}
		return redirectToList();
	}

}
