/*
 * Created on 16 Mar 2017 ( Time 18:41:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import net.kumasi.storytime.web.common.AbstractController;
import net.kumasi.storytime.web.common.FormMode;
import net.kumasi.storytime.web.common.Message;
import net.kumasi.storytime.web.common.MessageType;

//--- Entities
import net.kumasi.storytime.model.Requirement;
import net.kumasi.storytime.model.SpecificationType;
import net.kumasi.storytime.model.StatusCode;

//--- Services 
import net.kumasi.storytime.business.service.RequirementService;
import net.kumasi.storytime.business.service.SpecificationTypeService;
import net.kumasi.storytime.business.service.StatusCodeService;

//--- List Items 
import net.kumasi.storytime.web.listitem.SpecificationTypeListItem;
import net.kumasi.storytime.web.listitem.StatusCodeListItem;

/**
 * Spring MVC controller for 'Requirement' management.
 */
@Controller
@RequestMapping("/requirement")
public class RequirementController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "requirement";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "requirement/form";
	private static final String JSP_LIST   = "requirement/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/requirement/create";
	private static final String SAVE_ACTION_UPDATE   = "/requirement/update";

	//--- Main entity service
	@Resource
    private RequirementService requirementService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private SpecificationTypeService specificationTypeService; // Injected by Spring
	@Resource
    private StatusCodeService statusCodeService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public RequirementController() {
		super(RequirementController.class, MAIN_ENTITY_NAME );
		log("RequirementController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "SpecificationType"
	 * @param model
	 */
	private void populateListOfSpecificationTypeItems(Model model) {
		List<SpecificationType> list = specificationTypeService.findAll();
		List<SpecificationTypeListItem> items = new LinkedList<SpecificationTypeListItem>();
		for ( SpecificationType specificationType : list ) {
			items.add(new SpecificationTypeListItem( specificationType ) );
		}
		model.addAttribute("listOfSpecificationTypeItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "StatusCode"
	 * @param model
	 */
	private void populateListOfStatusCodeItems(Model model) {
		List<StatusCode> list = statusCodeService.findAll();
		List<StatusCodeListItem> items = new LinkedList<StatusCodeListItem>();
		for ( StatusCode statusCode : list ) {
			items.add(new StatusCodeListItem( statusCode ) );
		}
		model.addAttribute("listOfStatusCodeItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param requirement
	 */
	private void populateModel(Model model, Requirement requirement, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, requirement);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfSpecificationTypeItems(model);
			populateListOfStatusCodeItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfStatusCodeItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of Requirement found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<Requirement> list = requirementService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new Requirement
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		Requirement requirement = new Requirement();	
		populateModel( model, requirement, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing Requirement
	 * @param model Spring MVC model
	 * @param idrequirement  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{idrequirement}")
	public String formForUpdate(Model model, @PathVariable("idrequirement") Integer idrequirement ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		Requirement requirement = requirementService.findById(idrequirement);
		populateModel( model, requirement, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param requirement  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid Requirement requirement, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				Requirement requirementCreated = requirementService.create(requirement); 
				model.addAttribute(MAIN_ENTITY_NAME, requirementCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, requirement.getIdrequirement() );
			} else {
				populateModel( model, requirement, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "requirement.error.create", e);
			populateModel( model, requirement, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param requirement  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid Requirement requirement, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				Requirement requirementSaved = requirementService.update(requirement);
				model.addAttribute(MAIN_ENTITY_NAME, requirementSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, requirement.getIdrequirement());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, requirement, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "requirement.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, requirement, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param idrequirement  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{idrequirement}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("idrequirement") Integer idrequirement) {
		log("Action 'delete'" );
		try {
			requirementService.delete( idrequirement );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "requirement.error.delete", e);
		}
		return redirectToList();
	}

}
