/*
 * Created on 16 Mar 2017 ( Time 18:41:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.web.controller;

import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import net.kumasi.storytime.web.common.AbstractController;
import net.kumasi.storytime.web.common.FormMode;
import net.kumasi.storytime.web.common.Message;
import net.kumasi.storytime.web.common.MessageType;

//--- Entities
import net.kumasi.storytime.model.SpecificationType;

//--- Services 
import net.kumasi.storytime.business.service.SpecificationTypeService;


/**
 * Spring MVC controller for 'SpecificationType' management.
 */
@Controller
@RequestMapping("/specificationType")
public class SpecificationTypeController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "specificationType";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "specificationType/form";
	private static final String JSP_LIST   = "specificationType/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/specificationType/create";
	private static final String SAVE_ACTION_UPDATE   = "/specificationType/update";

	//--- Main entity service
	@Resource
    private SpecificationTypeService specificationTypeService; // Injected by Spring
	//--- Other service(s)

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public SpecificationTypeController() {
		super(SpecificationTypeController.class, MAIN_ENTITY_NAME );
		log("SpecificationTypeController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------

	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param specificationType
	 */
	private void populateModel(Model model, SpecificationType specificationType, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, specificationType);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of SpecificationType found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<SpecificationType> list = specificationTypeService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new SpecificationType
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		SpecificationType specificationType = new SpecificationType();	
		populateModel( model, specificationType, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing SpecificationType
	 * @param model Spring MVC model
	 * @param idrequirementType  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{idrequirementType}")
	public String formForUpdate(Model model, @PathVariable("idrequirementType") Integer idrequirementType ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		SpecificationType specificationType = specificationTypeService.findById(idrequirementType);
		populateModel( model, specificationType, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param specificationType  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid SpecificationType specificationType, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				SpecificationType specificationTypeCreated = specificationTypeService.create(specificationType); 
				model.addAttribute(MAIN_ENTITY_NAME, specificationTypeCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, specificationType.getIdrequirementType() );
			} else {
				populateModel( model, specificationType, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "specificationType.error.create", e);
			populateModel( model, specificationType, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param specificationType  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid SpecificationType specificationType, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				SpecificationType specificationTypeSaved = specificationTypeService.update(specificationType);
				model.addAttribute(MAIN_ENTITY_NAME, specificationTypeSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, specificationType.getIdrequirementType());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, specificationType, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "specificationType.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, specificationType, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param idrequirementType  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{idrequirementType}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("idrequirementType") Integer idrequirementType) {
		log("Action 'delete'" );
		try {
			specificationTypeService.delete( idrequirementType );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "specificationType.error.delete", e);
		}
		return redirectToList();
	}

}
