/*
 * Created on 16 Mar 2017 ( Time 18:41:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.test.persistence;


import net.kumasi.storytime.model.jpa.RequirementSpecificationTypeEntity;
import net.kumasi.storytime.mock.RequirementSpecificationTypeEntityMock;
import net.kumasi.storytime.persistence.PersistenceServiceProvider;
import net.kumasi.storytime.persistence.services.RequirementSpecificationTypePersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for RequirementSpecificationType persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class RequirementSpecificationTypePersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		RequirementSpecificationTypePersistence service = PersistenceServiceProvider.getService(RequirementSpecificationTypePersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test RequirementSpecificationType persistence : delete + load ..." );
		
		RequirementSpecificationTypePersistence service = PersistenceServiceProvider.getService(RequirementSpecificationTypePersistence.class);
		
		RequirementSpecificationTypeEntityMock mock = new RequirementSpecificationTypeEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0 , 0  );
		// process( service, mock, ... );
	}

	private void process(RequirementSpecificationTypePersistence service, RequirementSpecificationTypeEntityMock mock, Integer requirementIdrequirement, Integer specificationTypeIdrequirementType ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		RequirementSpecificationTypeEntity entity = service.load( requirementIdrequirement, specificationTypeIdrequirementType );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( requirementIdrequirement, specificationTypeIdrequirementType ) ;
			Assert.assertNotNull(entity);

			/* NB : this entity is a "Join Table" 
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			*/

			System.out.println(" . delete : " );
			boolean deleted = service.delete( requirementIdrequirement, specificationTypeIdrequirementType );
			System.out.println("   deleted = " + deleted);
		}		
	}
}
