/*
 * Created on 16 Mar 2017 ( Time 18:41:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.test.persistence;


import net.kumasi.storytime.model.jpa.RequirementEntity;
import net.kumasi.storytime.mock.RequirementEntityMock;
import net.kumasi.storytime.persistence.PersistenceServiceProvider;
import net.kumasi.storytime.persistence.services.RequirementPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Requirement persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class RequirementPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		RequirementPersistence service = PersistenceServiceProvider.getService(RequirementPersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test Requirement persistence : delete + load ..." );
		
		RequirementPersistence service = PersistenceServiceProvider.getService(RequirementPersistence.class);
		
		RequirementEntityMock mock = new RequirementEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0  );
		// process( service, mock, ... );
	}

	private void process(RequirementPersistence service, RequirementEntityMock mock, Integer idrequirement ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		RequirementEntity entity = service.load( idrequirement );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( idrequirement ) ;
			Assert.assertNotNull(entity);

			// This entity references the following entities : 
			// . StatusCode
			/* Insert only if references are OK
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			*/

			System.out.println(" . delete : " );
			boolean deleted = service.delete( idrequirement );
			System.out.println("   deleted = " + deleted);
		}		
	}
}
