/*
 * Created on 16 Mar 2017 ( Time 18:41:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.test.persistence;


import net.kumasi.storytime.model.jpa.SpecificationTypeEntity;
import net.kumasi.storytime.mock.SpecificationTypeEntityMock;
import net.kumasi.storytime.persistence.PersistenceServiceProvider;
import net.kumasi.storytime.persistence.services.SpecificationTypePersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for SpecificationType persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class SpecificationTypePersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		SpecificationTypePersistence service = PersistenceServiceProvider.getService(SpecificationTypePersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test SpecificationType persistence : delete + load ..." );
		
		SpecificationTypePersistence service = PersistenceServiceProvider.getService(SpecificationTypePersistence.class);
		
		SpecificationTypeEntityMock mock = new SpecificationTypeEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0  );
		// process( service, mock, ... );
	}

	private void process(SpecificationTypePersistence service, SpecificationTypeEntityMock mock, Integer idrequirementType ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		SpecificationTypeEntity entity = service.load( idrequirementType );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( idrequirementType ) ;
			Assert.assertNotNull(entity);

			// No reference : insert is possible 
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );

			System.out.println(" . delete : " );
			boolean deleted = service.delete( idrequirementType );
			System.out.println("   deleted = " + deleted);
			Assert.assertTrue(deleted) ;
		}		
	}
}
