
/*
 * Created on 16 Mar 2017 ( Time 18:41:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.mock;

import java.util.LinkedList;
import java.util.List;

import net.kumasi.storytime.model.jpa.CommentEntity;
import net.kumasi.storytime.mock.tool.MockValues;

public class CommentEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public CommentEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public CommentEntity createInstance( Integer idcomment ) {
		CommentEntity entity = new CommentEntity();
		// Init Primary Key fields
		entity.setIdcomment( idcomment) ;
		// Init Data fields
		entity.setDescription( mockValues.nextString(16777215) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setRequirement( TODO ) ; // Requirement 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<CommentEntity> createList(int count) {
		List<CommentEntity> list = new LinkedList<CommentEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
