
/*
 * Created on 16 Mar 2017 ( Time 18:41:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.mock;

import java.util.LinkedList;
import java.util.List;

import net.kumasi.storytime.model.jpa.RequirementEntity;
import net.kumasi.storytime.mock.tool.MockValues;

public class RequirementEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public RequirementEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public RequirementEntity createInstance( Integer idrequirement ) {
		RequirementEntity entity = new RequirementEntity();
		// Init Primary Key fields
		entity.setIdrequirement( idrequirement) ;
		// Init Data fields
		entity.setTitle( mockValues.nextString(75) ) ; // java.lang.String 
		entity.setDescription( mockValues.nextString(16777215) ) ; // java.lang.String 
		entity.setAcceptanceCriteria( mockValues.nextString(16777215) ) ; // java.lang.String 
		entity.setCreatedOn( mockValues.nextDate() ) ; // java.util.Date 
		entity.setCreatedBy( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setStartDate( mockValues.nextDate() ) ; // java.util.Date 
		entity.setEndDate( mockValues.nextDate() ) ; // java.util.Date 
		entity.setStatus( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setPriority( mockValues.nextInteger() ) ; // java.lang.Integer 
		// Init Link fields (if any)
		// setListOfSpecificationType( TODO ) ; // List<SpecificationType> 
		// setStatusCode( TODO ) ; // StatusCode 
		// setListOfComment( TODO ) ; // List<Comment> 
		// setListOfPersonAssignment( TODO ) ; // List<PersonAssignment> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<RequirementEntity> createList(int count) {
		List<RequirementEntity> list = new LinkedList<RequirementEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
