
/*
 * Created on 16 Mar 2017 ( Time 18:41:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.mock;

import java.util.LinkedList;
import java.util.List;

import net.kumasi.storytime.model.jpa.RequirementSpecificationTypeEntity;
import net.kumasi.storytime.mock.tool.MockValues;

public class RequirementSpecificationTypeEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public RequirementSpecificationTypeEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger(), mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public RequirementSpecificationTypeEntity createInstance( Integer requirementIdrequirement, Integer specificationTypeIdrequirementType ) {
		RequirementSpecificationTypeEntity entity = new RequirementSpecificationTypeEntity();
		// Init Primary Key fields
		entity.setRequirementIdrequirement( requirementIdrequirement) ;
		entity.setSpecificationTypeIdrequirementType( specificationTypeIdrequirementType) ;
		// Init Data fields
		// Init Link fields (if any)
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<RequirementSpecificationTypeEntity> createList(int count) {
		List<RequirementSpecificationTypeEntity> list = new LinkedList<RequirementSpecificationTypeEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
