
/*
 * Created on 16 Mar 2017 ( Time 18:41:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.mock;

import java.util.LinkedList;
import java.util.List;

import net.kumasi.storytime.model.jpa.SpecificationTypeEntity;
import net.kumasi.storytime.mock.tool.MockValues;

public class SpecificationTypeEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public SpecificationTypeEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public SpecificationTypeEntity createInstance( Integer idrequirementType ) {
		SpecificationTypeEntity entity = new SpecificationTypeEntity();
		// Init Primary Key fields
		entity.setIdrequirementType( idrequirementType) ;
		// Init Data fields
		entity.setName( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setDescription( mockValues.nextString(500) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setListOfRequirement( TODO ) ; // List<Requirement> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<SpecificationTypeEntity> createList(int count) {
		List<SpecificationTypeEntity> list = new LinkedList<SpecificationTypeEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
