
/*
 * Created on 16 Mar 2017 ( Time 18:41:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.mock;

import java.util.LinkedList;
import java.util.List;

import net.kumasi.storytime.model.jpa.StatusCodeEntity;
import net.kumasi.storytime.mock.tool.MockValues;

public class StatusCodeEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public StatusCodeEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public StatusCodeEntity createInstance( Integer id ) {
		StatusCodeEntity entity = new StatusCodeEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setCode( mockValues.nextString(45) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setListOfRequirement( TODO ) ; // List<Requirement> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<StatusCodeEntity> createList(int count) {
		List<StatusCodeEntity> list = new LinkedList<StatusCodeEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
