/*
 * Created on 16 Mar 2017 ( Time 18:41:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.web.common;

public interface ListItem {

	public String getValue();
	
	public String getLabel();
}
