/*
 * Created on 16 Mar 2017 ( Time 18:41:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import net.kumasi.storytime.model.PersonAssignment;
import net.kumasi.storytime.model.jpa.PersonAssignmentEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class PersonAssignmentServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public PersonAssignmentServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'PersonAssignmentEntity' to 'PersonAssignment'
	 * @param personAssignmentEntity
	 */
	public PersonAssignment mapPersonAssignmentEntityToPersonAssignment(PersonAssignmentEntity personAssignmentEntity) {
		if(personAssignmentEntity == null) {
			return null;
		}

		//--- Generic mapping 
		PersonAssignment personAssignment = map(personAssignmentEntity, PersonAssignment.class);

		return personAssignment;
	}
	
	/**
	 * Mapping from 'PersonAssignment' to 'PersonAssignmentEntity'
	 * @param personAssignment
	 * @param personAssignmentEntity
	 */
	public void mapPersonAssignmentToPersonAssignmentEntity(PersonAssignment personAssignment, PersonAssignmentEntity personAssignmentEntity) {
		if(personAssignment == null) {
			return;
		}

		//--- Generic mapping 
		map(personAssignment, personAssignmentEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}