/*
 * Created on 16 Mar 2017 ( Time 18:41:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import net.kumasi.storytime.model.StatusCode;
import net.kumasi.storytime.model.jpa.StatusCodeEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class StatusCodeServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public StatusCodeServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'StatusCodeEntity' to 'StatusCode'
	 * @param statusCodeEntity
	 */
	public StatusCode mapStatusCodeEntityToStatusCode(StatusCodeEntity statusCodeEntity) {
		if(statusCodeEntity == null) {
			return null;
		}

		//--- Generic mapping 
		StatusCode statusCode = map(statusCodeEntity, StatusCode.class);

		return statusCode;
	}
	
	/**
	 * Mapping from 'StatusCode' to 'StatusCodeEntity'
	 * @param statusCode
	 * @param statusCodeEntity
	 */
	public void mapStatusCodeToStatusCodeEntity(StatusCode statusCode, StatusCodeEntity statusCodeEntity) {
		if(statusCode == null) {
			return;
		}

		//--- Generic mapping 
		map(statusCode, statusCodeEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}