/*
 * Created on 16 Mar 2017 ( Time 18:41:45 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import net.kumasi.storytime.model.Person;
import net.kumasi.storytime.model.jpa.PersonEntity;
import net.kumasi.storytime.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class PersonServiceMapperTest {

	private PersonServiceMapper personServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		personServiceMapper = new PersonServiceMapper();
		personServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'PersonEntity' to 'Person'
	 * @param personEntity
	 */
	@Test
	public void testMapPersonEntityToPerson() {
		// Given
		PersonEntity personEntity = new PersonEntity();
		personEntity.setFirstName(mockValues.nextString(45));
		personEntity.setLastName(mockValues.nextString(45));
		
		// When
		Person person = personServiceMapper.mapPersonEntityToPerson(personEntity);
		
		// Then
		assertEquals(personEntity.getFirstName(), person.getFirstName());
		assertEquals(personEntity.getLastName(), person.getLastName());
	}
	
	/**
	 * Test : Mapping from 'Person' to 'PersonEntity'
	 */
	@Test
	public void testMapPersonToPersonEntity() {
		// Given
		Person person = new Person();
		person.setFirstName(mockValues.nextString(45));
		person.setLastName(mockValues.nextString(45));

		PersonEntity personEntity = new PersonEntity();
		
		// When
		personServiceMapper.mapPersonToPersonEntity(person, personEntity);
		
		// Then
		assertEquals(person.getFirstName(), personEntity.getFirstName());
		assertEquals(person.getLastName(), personEntity.getLastName());
	}

}