/*
 * Created on 16 Mar 2017 ( Time 18:41:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import net.kumasi.storytime.model.RequirementSpecificationType;
import net.kumasi.storytime.model.jpa.RequirementSpecificationTypeEntity;
import net.kumasi.storytime.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class RequirementSpecificationTypeServiceMapperTest {

	private RequirementSpecificationTypeServiceMapper requirementSpecificationTypeServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		requirementSpecificationTypeServiceMapper = new RequirementSpecificationTypeServiceMapper();
		requirementSpecificationTypeServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'RequirementSpecificationTypeEntity' to 'RequirementSpecificationType'
	 * @param requirementSpecificationTypeEntity
	 */
	@Test
	public void testMapRequirementSpecificationTypeEntityToRequirementSpecificationType() {
		// Given
		RequirementSpecificationTypeEntity requirementSpecificationTypeEntity = new RequirementSpecificationTypeEntity();
		
		// When
		RequirementSpecificationType requirementSpecificationType = requirementSpecificationTypeServiceMapper.mapRequirementSpecificationTypeEntityToRequirementSpecificationType(requirementSpecificationTypeEntity);
		
		// Then
	}
	
	/**
	 * Test : Mapping from 'RequirementSpecificationType' to 'RequirementSpecificationTypeEntity'
	 */
	@Test
	public void testMapRequirementSpecificationTypeToRequirementSpecificationTypeEntity() {
		// Given
		RequirementSpecificationType requirementSpecificationType = new RequirementSpecificationType();

		RequirementSpecificationTypeEntity requirementSpecificationTypeEntity = new RequirementSpecificationTypeEntity();
		
		// When
		requirementSpecificationTypeServiceMapper.mapRequirementSpecificationTypeToRequirementSpecificationTypeEntity(requirementSpecificationType, requirementSpecificationTypeEntity);
		
		// Then
	}

}