/*
 * Created on 16 Mar 2017 ( Time 18:41:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import net.kumasi.storytime.model.SpecificationType;
import net.kumasi.storytime.model.jpa.SpecificationTypeEntity;
import net.kumasi.storytime.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class SpecificationTypeServiceMapperTest {

	private SpecificationTypeServiceMapper specificationTypeServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		specificationTypeServiceMapper = new SpecificationTypeServiceMapper();
		specificationTypeServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'SpecificationTypeEntity' to 'SpecificationType'
	 * @param specificationTypeEntity
	 */
	@Test
	public void testMapSpecificationTypeEntityToSpecificationType() {
		// Given
		SpecificationTypeEntity specificationTypeEntity = new SpecificationTypeEntity();
		specificationTypeEntity.setName(mockValues.nextString(45));
		specificationTypeEntity.setDescription(mockValues.nextString(500));
		
		// When
		SpecificationType specificationType = specificationTypeServiceMapper.mapSpecificationTypeEntityToSpecificationType(specificationTypeEntity);
		
		// Then
		assertEquals(specificationTypeEntity.getName(), specificationType.getName());
		assertEquals(specificationTypeEntity.getDescription(), specificationType.getDescription());
	}
	
	/**
	 * Test : Mapping from 'SpecificationType' to 'SpecificationTypeEntity'
	 */
	@Test
	public void testMapSpecificationTypeToSpecificationTypeEntity() {
		// Given
		SpecificationType specificationType = new SpecificationType();
		specificationType.setName(mockValues.nextString(45));
		specificationType.setDescription(mockValues.nextString(500));

		SpecificationTypeEntity specificationTypeEntity = new SpecificationTypeEntity();
		
		// When
		specificationTypeServiceMapper.mapSpecificationTypeToSpecificationTypeEntity(specificationType, specificationTypeEntity);
		
		// Then
		assertEquals(specificationType.getName(), specificationTypeEntity.getName());
		assertEquals(specificationType.getDescription(), specificationTypeEntity.getDescription());
	}

}