/*
 * Created on 16 Mar 2017 ( Time 18:41:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import net.kumasi.storytime.model.StatusCode;
import net.kumasi.storytime.model.jpa.StatusCodeEntity;
import net.kumasi.storytime.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class StatusCodeServiceMapperTest {

	private StatusCodeServiceMapper statusCodeServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		statusCodeServiceMapper = new StatusCodeServiceMapper();
		statusCodeServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'StatusCodeEntity' to 'StatusCode'
	 * @param statusCodeEntity
	 */
	@Test
	public void testMapStatusCodeEntityToStatusCode() {
		// Given
		StatusCodeEntity statusCodeEntity = new StatusCodeEntity();
		statusCodeEntity.setCode(mockValues.nextString(45));
		
		// When
		StatusCode statusCode = statusCodeServiceMapper.mapStatusCodeEntityToStatusCode(statusCodeEntity);
		
		// Then
		assertEquals(statusCodeEntity.getCode(), statusCode.getCode());
	}
	
	/**
	 * Test : Mapping from 'StatusCode' to 'StatusCodeEntity'
	 */
	@Test
	public void testMapStatusCodeToStatusCodeEntity() {
		// Given
		StatusCode statusCode = new StatusCode();
		statusCode.setCode(mockValues.nextString(45));

		StatusCodeEntity statusCodeEntity = new StatusCodeEntity();
		
		// When
		statusCodeServiceMapper.mapStatusCodeToStatusCodeEntity(statusCode, statusCodeEntity);
		
		// Then
		assertEquals(statusCode.getCode(), statusCodeEntity.getCode());
	}

}