/*
 * Created on 16 Mar 2017 ( Time 18:41:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.persistence.services.fake;

import java.util.List;
import java.util.Map;

import net.kumasi.storytime.model.jpa.RequirementSpecificationTypeEntity;
import net.kumasi.storytime.persistence.commons.fake.GenericFakeService;
import net.kumasi.storytime.persistence.services.RequirementSpecificationTypePersistence;

/**
 * Fake persistence service implementation ( entity "RequirementSpecificationType" )
 *
 * @author Telosys Tools Generator
 */
public class RequirementSpecificationTypePersistenceFAKE extends GenericFakeService<RequirementSpecificationTypeEntity> implements RequirementSpecificationTypePersistence {

	public RequirementSpecificationTypePersistenceFAKE () {
		super(RequirementSpecificationTypeEntity.class);
	}
	
	protected RequirementSpecificationTypeEntity buildEntity(int index) {
		RequirementSpecificationTypeEntity entity = new RequirementSpecificationTypeEntity();
		// Init fields with mock values
		entity.setRequirementIdrequirement( nextInteger() ) ;
		entity.setSpecificationTypeIdrequirementType( nextInteger() ) ;
		return entity ;
	}
	
	
	public boolean delete(RequirementSpecificationTypeEntity entity) {
		log("delete ( RequirementSpecificationTypeEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer requirementIdrequirement, Integer specificationTypeIdrequirementType ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(RequirementSpecificationTypeEntity entity) {
		log("insert ( RequirementSpecificationTypeEntity : " + entity + ")" ) ;
	}

	public RequirementSpecificationTypeEntity load( Integer requirementIdrequirement, Integer specificationTypeIdrequirementType ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<RequirementSpecificationTypeEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<RequirementSpecificationTypeEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<RequirementSpecificationTypeEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public RequirementSpecificationTypeEntity save(RequirementSpecificationTypeEntity entity) {
		log("insert ( RequirementSpecificationTypeEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<RequirementSpecificationTypeEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
