/*
 * Created on 16 Mar 2017 ( Time 18:41:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.persistence.services.fake;

import java.util.List;
import java.util.Map;

import net.kumasi.storytime.model.jpa.StatusCodeEntity;
import net.kumasi.storytime.persistence.commons.fake.GenericFakeService;
import net.kumasi.storytime.persistence.services.StatusCodePersistence;

/**
 * Fake persistence service implementation ( entity "StatusCode" )
 *
 * @author Telosys Tools Generator
 */
public class StatusCodePersistenceFAKE extends GenericFakeService<StatusCodeEntity> implements StatusCodePersistence {

	public StatusCodePersistenceFAKE () {
		super(StatusCodeEntity.class);
	}
	
	protected StatusCodeEntity buildEntity(int index) {
		StatusCodeEntity entity = new StatusCodeEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setCode( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(StatusCodeEntity entity) {
		log("delete ( StatusCodeEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(StatusCodeEntity entity) {
		log("insert ( StatusCodeEntity : " + entity + ")" ) ;
	}

	public StatusCodeEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<StatusCodeEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<StatusCodeEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<StatusCodeEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public StatusCodeEntity save(StatusCodeEntity entity) {
		log("insert ( StatusCodeEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<StatusCodeEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
