/*
 * Created on 16 Mar 2017 ( Time 18:41:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a composite Primary Key  


package net.kumasi.storytime.model.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "requirement_specification_type"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="requirement_specification_type", catalog="storytime" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="RequirementSpecificationTypeEntity.countAll", query="SELECT COUNT(x) FROM RequirementSpecificationTypeEntity x" )
} )
public class RequirementSpecificationTypeEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
	@EmbeddedId
    private RequirementSpecificationTypeEntityKey compositePrimaryKey ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public RequirementSpecificationTypeEntity() {
		super();
		this.compositePrimaryKey = new RequirementSpecificationTypeEntityKey();       
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------
    public void setRequirementIdrequirement( Integer requirementIdrequirement ) {
        this.compositePrimaryKey.setRequirementIdrequirement( requirementIdrequirement ) ;
    }
    public Integer getRequirementIdrequirement() {
        return this.compositePrimaryKey.getRequirementIdrequirement() ;
    }
    public void setSpecificationTypeIdrequirementType( Integer specificationTypeIdrequirementType ) {
        this.compositePrimaryKey.setSpecificationTypeIdrequirementType( specificationTypeIdrequirementType ) ;
    }
    public Integer getSpecificationTypeIdrequirementType() {
        return this.compositePrimaryKey.getSpecificationTypeIdrequirementType() ;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        if ( compositePrimaryKey != null ) {  
            sb.append(compositePrimaryKey.toString());  
        }  
        else {  
            sb.append( "(null-key)" ); 
        }  
        sb.append("]:"); 
        return sb.toString(); 
    } 

}
