/*
 * Created on 16 Mar 2017 ( Time 18:41:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.web.listitem;

import net.kumasi.storytime.model.Comment;
import net.kumasi.storytime.web.common.ListItem;

public class CommentListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public CommentListItem(Comment comment) {
		super();

		this.value = ""
			 + comment.getIdcomment()
		;

		//TODO : Define here the attributes to be displayed as the label
		if(comment.getDescription() != null && comment.getDescription().length() >= 15) {
			this.label = comment.getDescription().substring(0,15);
		}else{
			this.label = comment.getDescription();
		}
		
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
