/*
 * Created on 16 Mar 2017 ( Time 18:41:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.web.listitem;

import net.kumasi.storytime.model.PersonAssignment;
import net.kumasi.storytime.web.common.ListItem;

public class PersonAssignmentListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public PersonAssignmentListItem(PersonAssignment personAssignment) {
		super();

		this.value = ""
			 + personAssignment.getPersonIdperson()
			 + "|"  + personAssignment.getRequirementIdrequirement()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = personAssignment.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
