/*
 * Created on 16 Mar 2017 ( Time 18:41:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.web.listitem;

import net.kumasi.storytime.model.Requirement;
import net.kumasi.storytime.web.common.ListItem;

public class RequirementListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public RequirementListItem(Requirement requirement) {
		super();

		this.value = ""
			 + requirement.getIdrequirement()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = requirement.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
