/*
 * Created on 16 Mar 2017 ( Time 18:41:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.web.listitem;

import net.kumasi.storytime.model.RequirementSpecificationType;
import net.kumasi.storytime.web.common.ListItem;

public class RequirementSpecificationTypeListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public RequirementSpecificationTypeListItem(RequirementSpecificationType requirementSpecificationType) {
		super();

		this.value = ""
			 + requirementSpecificationType.getRequirementIdrequirement()
			 + "|"  + requirementSpecificationType.getSpecificationTypeIdrequirementType()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = requirementSpecificationType.getRequirementIdrequirement().toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
