/*
 * Created on 16 Mar 2017 ( Time 18:41:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.web.listitem;

import net.kumasi.storytime.model.StatusCode;
import net.kumasi.storytime.web.common.ListItem;

public class StatusCodeListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public StatusCodeListItem(StatusCode statusCode) {
		super();

		this.value = ""
			 + statusCode.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = statusCode.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
