/*
 * Created on 16 Mar 2017 ( Time 18:41:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.business.service;

import java.util.List;

import net.kumasi.storytime.model.Person;

/**
 * Business Service Interface for entity Person.
 */
public interface PersonService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idperson
	 * @return entity
	 */
	Person findById( Integer idperson  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Person> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Person save(Person entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Person update(Person entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Person create(Person entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idperson
	 */
	void delete( Integer idperson );


}
