/*
 * Created on 16 Mar 2017 ( Time 18:41:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.business.service;

import java.util.List;

import net.kumasi.storytime.model.RequirementSpecificationType;

/**
 * Business Service Interface for entity RequirementSpecificationType.
 */
public interface RequirementSpecificationTypeService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param requirementIdrequirement
	 * @param specificationTypeIdrequirementType
	 * @return entity
	 */
	RequirementSpecificationType findById( Integer requirementIdrequirement, Integer specificationTypeIdrequirementType  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<RequirementSpecificationType> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	RequirementSpecificationType save(RequirementSpecificationType entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	RequirementSpecificationType update(RequirementSpecificationType entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	RequirementSpecificationType create(RequirementSpecificationType entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param requirementIdrequirement
	 * @param specificationTypeIdrequirementType
	 */
	void delete( Integer requirementIdrequirement, Integer specificationTypeIdrequirementType );


}
