/*
 * Created on 16 Mar 2017 ( Time 18:41:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.business.service;

import java.util.List;

import net.kumasi.storytime.model.Requirement;

/**
 * Business Service Interface for entity Requirement.
 */
public interface RequirementService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idrequirement
	 * @return entity
	 */
	Requirement findById( Integer idrequirement  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Requirement> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Requirement save(Requirement entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Requirement update(Requirement entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Requirement create(Requirement entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idrequirement
	 */
	void delete( Integer idrequirement );


}
