/*
 * Created on 16 Mar 2017 ( Time 18:41:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.business.service;

import java.util.List;

import net.kumasi.storytime.model.SpecificationType;

/**
 * Business Service Interface for entity SpecificationType.
 */
public interface SpecificationTypeService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idrequirementType
	 * @return entity
	 */
	SpecificationType findById( Integer idrequirementType  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<SpecificationType> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	SpecificationType save(SpecificationType entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	SpecificationType update(SpecificationType entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	SpecificationType create(SpecificationType entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idrequirementType
	 */
	void delete( Integer idrequirementType );


}
