/*
 * Created on 16 Mar 2017 ( Time 18:41:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.business.service;

import java.util.List;

import net.kumasi.storytime.model.StatusCode;

/**
 * Business Service Interface for entity StatusCode.
 */
public interface StatusCodeService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	StatusCode findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<StatusCode> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	StatusCode save(StatusCode entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	StatusCode update(StatusCode entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	StatusCode create(StatusCode entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
