/*
 * Created on 16 Mar 2017 ( Time 18:41:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package net.kumasi.storytime.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import net.kumasi.storytime.model.jpa.CommentEntity;
import net.kumasi.storytime.persistence.commons.jpa.GenericJpaService;
import net.kumasi.storytime.persistence.commons.jpa.JpaOperation;
import net.kumasi.storytime.persistence.services.CommentPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Comment" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class CommentPersistenceJPA extends GenericJpaService<CommentEntity, Integer> implements CommentPersistence {

	/**
	 * Constructor
	 */
	public CommentPersistenceJPA() {
		super(CommentEntity.class);
	}

	@Override
	public CommentEntity load( Integer idcomment ) {
		return super.load( idcomment );
	}

	@Override
	public boolean delete( Integer idcomment ) {
		return super.delete( idcomment );
	}

	@Override
	public boolean delete(CommentEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getIdcomment() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("CommentEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
