/*
 * Created on 16 Mar 2017 ( Time 18:41:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package net.kumasi.storytime.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import net.kumasi.storytime.model.jpa.PersonAssignmentEntity;
import net.kumasi.storytime.model.jpa.PersonAssignmentEntityKey;
import net.kumasi.storytime.persistence.commons.jpa.GenericJpaService;
import net.kumasi.storytime.persistence.commons.jpa.JpaOperation;
import net.kumasi.storytime.persistence.services.PersonAssignmentPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "PersonAssignment" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class PersonAssignmentPersistenceJPA extends GenericJpaService<PersonAssignmentEntity, PersonAssignmentEntityKey> implements PersonAssignmentPersistence {

	/**
	 * Constructor
	 */
	public PersonAssignmentPersistenceJPA() {
		super(PersonAssignmentEntity.class);
	}

	@Override
	public PersonAssignmentEntity load( Integer personIdperson, Integer requirementIdrequirement ) {
		// Build the composite key
		PersonAssignmentEntityKey key = new PersonAssignmentEntityKey( personIdperson, requirementIdrequirement );
		return super.load( key );
	}

	@Override
	public boolean delete( Integer personIdperson, Integer requirementIdrequirement ) {
		// Build the composite key
		PersonAssignmentEntityKey key = new PersonAssignmentEntityKey( personIdperson, requirementIdrequirement );
		return super.delete( key );
	}

	@Override
	public boolean delete(PersonAssignmentEntity entity) {
		if ( entity != null ) {
			// Build the composite key
			PersonAssignmentEntityKey key = new PersonAssignmentEntityKey( entity.getPersonIdperson(), entity.getRequirementIdrequirement() );
			return super.delete( key );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("PersonAssignmentEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
