/*
 * Created on 16 Mar 2017 ( Time 18:41:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package net.kumasi.storytime.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import net.kumasi.storytime.model.jpa.RequirementEntity;
import net.kumasi.storytime.persistence.commons.jpa.GenericJpaService;
import net.kumasi.storytime.persistence.commons.jpa.JpaOperation;
import net.kumasi.storytime.persistence.services.RequirementPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Requirement" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class RequirementPersistenceJPA extends GenericJpaService<RequirementEntity, Integer> implements RequirementPersistence {

	/**
	 * Constructor
	 */
	public RequirementPersistenceJPA() {
		super(RequirementEntity.class);
	}

	@Override
	public RequirementEntity load( Integer idrequirement ) {
		return super.load( idrequirement );
	}

	@Override
	public boolean delete( Integer idrequirement ) {
		return super.delete( idrequirement );
	}

	@Override
	public boolean delete(RequirementEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getIdrequirement() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("RequirementEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
