/*
 * Created on 16 Mar 2017 ( Time 18:41:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package net.kumasi.storytime.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import net.kumasi.storytime.model.jpa.RequirementSpecificationTypeEntity;
import net.kumasi.storytime.model.jpa.RequirementSpecificationTypeEntityKey;
import net.kumasi.storytime.persistence.commons.jpa.GenericJpaService;
import net.kumasi.storytime.persistence.commons.jpa.JpaOperation;
import net.kumasi.storytime.persistence.services.RequirementSpecificationTypePersistence;

/**
 * JPA implementation for basic persistence operations ( entity "RequirementSpecificationType" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class RequirementSpecificationTypePersistenceJPA extends GenericJpaService<RequirementSpecificationTypeEntity, RequirementSpecificationTypeEntityKey> implements RequirementSpecificationTypePersistence {

	/**
	 * Constructor
	 */
	public RequirementSpecificationTypePersistenceJPA() {
		super(RequirementSpecificationTypeEntity.class);
	}

	@Override
	public RequirementSpecificationTypeEntity load( Integer requirementIdrequirement, Integer specificationTypeIdrequirementType ) {
		// Build the composite key
		RequirementSpecificationTypeEntityKey key = new RequirementSpecificationTypeEntityKey( requirementIdrequirement, specificationTypeIdrequirementType );
		return super.load( key );
	}

	@Override
	public boolean delete( Integer requirementIdrequirement, Integer specificationTypeIdrequirementType ) {
		// Build the composite key
		RequirementSpecificationTypeEntityKey key = new RequirementSpecificationTypeEntityKey( requirementIdrequirement, specificationTypeIdrequirementType );
		return super.delete( key );
	}

	@Override
	public boolean delete(RequirementSpecificationTypeEntity entity) {
		if ( entity != null ) {
			// Build the composite key
			RequirementSpecificationTypeEntityKey key = new RequirementSpecificationTypeEntityKey( entity.getRequirementIdrequirement(), entity.getSpecificationTypeIdrequirementType() );
			return super.delete( key );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("RequirementSpecificationTypeEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
