/*
 * Created on 16 Mar 2017 ( Time 18:41:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package net.kumasi.storytime.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import net.kumasi.storytime.model.jpa.SpecificationTypeEntity;
import net.kumasi.storytime.persistence.commons.jpa.GenericJpaService;
import net.kumasi.storytime.persistence.commons.jpa.JpaOperation;
import net.kumasi.storytime.persistence.services.SpecificationTypePersistence;

/**
 * JPA implementation for basic persistence operations ( entity "SpecificationType" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class SpecificationTypePersistenceJPA extends GenericJpaService<SpecificationTypeEntity, Integer> implements SpecificationTypePersistence {

	/**
	 * Constructor
	 */
	public SpecificationTypePersistenceJPA() {
		super(SpecificationTypeEntity.class);
	}

	@Override
	public SpecificationTypeEntity load( Integer idrequirementType ) {
		return super.load( idrequirementType );
	}

	@Override
	public boolean delete( Integer idrequirementType ) {
		return super.delete( idrequirementType );
	}

	@Override
	public boolean delete(SpecificationTypeEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getIdrequirementType() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("SpecificationTypeEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
