/*
 * Created on 16 Mar 2017 ( Time 18:41:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package net.kumasi.storytime.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import net.kumasi.storytime.model.jpa.StatusCodeEntity;
import net.kumasi.storytime.persistence.commons.jpa.GenericJpaService;
import net.kumasi.storytime.persistence.commons.jpa.JpaOperation;
import net.kumasi.storytime.persistence.services.StatusCodePersistence;

/**
 * JPA implementation for basic persistence operations ( entity "StatusCode" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class StatusCodePersistenceJPA extends GenericJpaService<StatusCodeEntity, Integer> implements StatusCodePersistence {

	/**
	 * Constructor
	 */
	public StatusCodePersistenceJPA() {
		super(StatusCodeEntity.class);
	}

	@Override
	public StatusCodeEntity load( Integer id ) {
		return super.load( id );
	}

	@Override
	public boolean delete( Integer id ) {
		return super.delete( id );
	}

	@Override
	public boolean delete(StatusCodeEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getId() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("StatusCodeEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
