/*
 * Created on 16 Mar 2017 ( Time 18:41:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.persistence.services;

import java.util.List;
import java.util.Map;

import net.kumasi.storytime.model.jpa.CommentEntity;

/**
 * Basic persistence operations for entity "Comment"
 * 
 * This Bean has a basic Primary Key : Integer
 *
 * @author Telosys Tools Generator
 *
 */
public interface CommentPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param comment
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(CommentEntity comment) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param idcomment
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Integer idcomment) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param comment
	 */
	public void insert(CommentEntity comment) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param idcomment
	 * @return the entity loaded (or null if not found)
	 */
	public CommentEntity load(Integer idcomment) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<CommentEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<CommentEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<CommentEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param comment
	 * @return
	 */
	public CommentEntity save(CommentEntity comment) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<CommentEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
	
}
