/*
 * Created on 16 Mar 2017 ( Time 18:41:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.persistence.services;

import java.util.List;
import java.util.Map;

import net.kumasi.storytime.model.jpa.PersonAssignmentEntity;

/**
 * Basic persistence operations for entity "PersonAssignment"
 * 
 * This Bean has a composite Primary Key : PersonAssignmentEntityKey
 *
 * @author Telosys Tools Generator
 *
 */
public interface PersonAssignmentPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param personAssignment
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(PersonAssignmentEntity personAssignment) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param personIdperson
	 * @param requirementIdrequirement
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Integer personIdperson, Integer requirementIdrequirement) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param personAssignment
	 */
	public void insert(PersonAssignmentEntity personAssignment) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param personIdperson
	 * @param requirementIdrequirement
	 * @return the entity loaded (or null if not found)
	 */
	public PersonAssignmentEntity load(Integer personIdperson, Integer requirementIdrequirement) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<PersonAssignmentEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<PersonAssignmentEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<PersonAssignmentEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param personAssignment
	 * @return
	 */
	public PersonAssignmentEntity save(PersonAssignmentEntity personAssignment) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<PersonAssignmentEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
	
}
