/*
 * Created on 16 Mar 2017 ( Time 18:41:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.persistence.services;

import java.util.List;
import java.util.Map;

import net.kumasi.storytime.model.jpa.RequirementSpecificationTypeEntity;

/**
 * Basic persistence operations for entity "RequirementSpecificationType"
 * 
 * This Bean has a composite Primary Key : RequirementSpecificationTypeEntityKey
 *
 * @author Telosys Tools Generator
 *
 */
public interface RequirementSpecificationTypePersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param requirementSpecificationType
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(RequirementSpecificationTypeEntity requirementSpecificationType) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param requirementIdrequirement
	 * @param specificationTypeIdrequirementType
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Integer requirementIdrequirement, Integer specificationTypeIdrequirementType) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param requirementSpecificationType
	 */
	public void insert(RequirementSpecificationTypeEntity requirementSpecificationType) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param requirementIdrequirement
	 * @param specificationTypeIdrequirementType
	 * @return the entity loaded (or null if not found)
	 */
	public RequirementSpecificationTypeEntity load(Integer requirementIdrequirement, Integer specificationTypeIdrequirementType) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<RequirementSpecificationTypeEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<RequirementSpecificationTypeEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<RequirementSpecificationTypeEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param requirementSpecificationType
	 * @return
	 */
	public RequirementSpecificationTypeEntity save(RequirementSpecificationTypeEntity requirementSpecificationType) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<RequirementSpecificationTypeEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
	
}
