/*
 * Created on 16 Mar 2017 ( Time 18:41:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.persistence.services;

import java.util.List;
import java.util.Map;

import net.kumasi.storytime.model.jpa.RequirementEntity;

/**
 * Basic persistence operations for entity "Requirement"
 * 
 * This Bean has a basic Primary Key : Integer
 *
 * @author Telosys Tools Generator
 *
 */
public interface RequirementPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param requirement
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(RequirementEntity requirement) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param idrequirement
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Integer idrequirement) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param requirement
	 */
	public void insert(RequirementEntity requirement) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param idrequirement
	 * @return the entity loaded (or null if not found)
	 */
	public RequirementEntity load(Integer idrequirement) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<RequirementEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<RequirementEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<RequirementEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param requirement
	 * @return
	 */
	public RequirementEntity save(RequirementEntity requirement) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<RequirementEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
	
}
