/*
 * Created on 16 Mar 2017 ( Time 18:41:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package net.kumasi.storytime.persistence.services;

import java.util.List;
import java.util.Map;

import net.kumasi.storytime.model.jpa.SpecificationTypeEntity;

/**
 * Basic persistence operations for entity "SpecificationType"
 * 
 * This Bean has a basic Primary Key : Integer
 *
 * @author Telosys Tools Generator
 *
 */
public interface SpecificationTypePersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param specificationType
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(SpecificationTypeEntity specificationType) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param idrequirementType
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Integer idrequirementType) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param specificationType
	 */
	public void insert(SpecificationTypeEntity specificationType) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param idrequirementType
	 * @return the entity loaded (or null if not found)
	 */
	public SpecificationTypeEntity load(Integer idrequirementType) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<SpecificationTypeEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<SpecificationTypeEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<SpecificationTypeEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param specificationType
	 * @return
	 */
	public SpecificationTypeEntity save(SpecificationTypeEntity specificationType) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<SpecificationTypeEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
	
}
